Lab2Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from app.views import *


urlpatterns = [
    url(r'^$', index),
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='app')),
]

app/urls.py
from django.conf.urls import url, include

from app.views import SuggestionView
from . import views

urlpatterns = [
        url(r'^$', views.index, name='index1'),
        url(r'^index/$', views.index, name='index'),
        url(r'^about/$', views.about, name='about'),
        url(r'^myacct/$', views.myacct, name='myacct'),
        url(r'^register/$', views.register, name='register'),
        url(r'^index/(?P<item_id>[0-9]+?)/$', views.detail, name='about'),
        url(r'^suggestions/$', views.suggestions, name='suggestions'),
        url(r'^newitem/$', views.newitem, name='newitem'),
        url(r'^searchitem/$', views.searchitem, name='searchitem'),
        url(r'^login/$', views.login_user, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
        url(r'^myitems/$', views.myitems, name='myitems'),
        url(r'^myitems/(?P<item_id>[0-9]+?)/$', views.detail, name='myitems'),
        url(r'^forgotpwd/$', views.forgotpwd, name='forgotpwd'),
        url(r'^checkuname/$', views.checkuname, name='checkuname'),
        url(r'^setpwd/$', views.setpwd, name='setpwd'),
        url(r'^suggestions/(?P<item_id>[0-9]+?)/$', SuggestionView.as_view())
    ]

app/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here


class Libuser(User):
    PROVINCE_CHOICES = (
        ('AB', 'Alberta'),  # The first value is actually stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    phone = models.IntegerField(null=True)
    profilepic = models.ImageField(upload_to='app/static/ProfilePics/', default='app/static/Profilepics/defaultpic.png')

    def __str__(self):
        return self.username


class Libitem(models.Model):
    TYPE_CHOICES = (
        ('Book', 'Book'),
        ('DVD', 'DVD'),
        ('Other', 'Other'),
    )
    title = models.CharField(max_length=100)
    itemtype = models.CharField(max_length=6, choices=TYPE_CHOICES, default='Book')
    checked_out = models.BooleanField(default=False)
    user = models.ForeignKey(Libuser, default=None, null=True, blank=True)
    duedate = models.DateField(default=None, null=True, blank=True)
    last_chkout = models.DateField(default=None, null=True, blank=True)
    date_acquired = models.DateField(default=datetime.date.today())
    pubyr = models.IntegerField()

    def __str__(self):
        return self.title

    def overdue(self):
        if self.checked_out and self.duedate:
            if self.duedate < datetime.date.today():
                return 'Yes'
            else:
                return 'No'


class Book(Libitem):
    CATEGORY_CHOICES = (
        (1, 'Fiction'),
        (2, 'Biography'),
        (3, 'Self Help'),
        (4, 'Education'),
        (5, 'Children'),
        (6, 'Teen'),
        (7, 'Other'),
    )
    author = models.CharField(max_length=100)
    category = models.IntegerField(choices=CATEGORY_CHOICES, default=1)

    def __str__(self):
        return self.title


class Dvd(Libitem):
    RATING_CHOICES = (
        ('G', 'G'),
        ('PG', 'PG'),
        ('PG-13', 'PG-13'),
        ('14A', '14A'),
        ('R', 'R'),
        ('NR', 'NR'),
    )
    maker = models.CharField(max_length=100)
    duration = models.IntegerField(help_text="In Minutes", default=0)
    rating = models.CharField(max_length=6, choices=RATING_CHOICES, default='G')

    def __str__(self):
        return self.maker + ' with ' + self.rating


class Suggestion(models.Model):
    TYPE_CHOICES = (
        (1, 'Book'),
        (2, 'DVD'),
        (3, 'Other'),
    )
    title = models.CharField(max_length=100)
    pubyr = models.IntegerField(null=True, blank=True)
    type = models.IntegerField(default=1, choices=TYPE_CHOICES)
    cost = models.IntegerField()
    num_interested = models.IntegerField()
    comments = models.TextField()

    def __str__(self):
        return self.title

templates/libapp/about.html
{% extends 'libapp/base.html' %}
{% block body_block %}
<br/>
    <div style="width: 26%; padding-left: 20px;float: left">
<h4 style="color: whitesmoke; text-decoration: underline" class="flow-text">Our Vision</h4><br/>
<h6 style="color: whitesmoke; padding-left: 20px" class="flow-text">Leddy Library continues to be known as an innovative community leader that inspires lifelong learning and literacy in a welcoming environment, while respecting and celebrating the unique diversity of Windsor.
<br/><br/></h6>

<h4 style="color: whitesmoke; text-decoration: underline" class="flow-text">Our Mission</h4><br/>
<h6 style="color: whitesmoke; padding-left: 20px" class="flow-text">Leddy Library engages the students of University of Windsor by providing a community gathering place where the joy of reading, discovery and lifelong learning is promoted and encouraged.</h6>
<br/>
        <h5 style="color: whitesmoke; padding-left: 10px" class="flow-text">No of hits: {{ about_visits }}</h5>
    </div>
    <div style="float:right; color: whitesmoke; padding-right: 10%; width: 30%"><br/>
            <h4 style="text-align: center">Hours of Operation</h4>
       <table class="table-responsive bordered centered">
           <tbody>
           <tr><td></td><td></td></tr>
        <tr><td>Monday</td><td>9:00 am-12 am</td></tr>
        <tr><td>Tuesday</td><td>9:00 am-12 am</td></tr>
        <tr><td>Wednesday</td><td>7:00 am-12 am</td></tr>
            <tr><td>Thursday</td><td>7:00 am-12 am</td></tr>
            <tr><td>Friday</td><td>7:00 am-12 am</td></tr>
            <tr><td>Saturday</td><td>7:00 am-12 am</td></tr>
            <tr><td>Sunday</td><td>7:00 am-12:00 am</td></tr>
           </tbody>
        </table>
        </div>
    </div>
{% endblock %}

templates/libapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>{% block head %}
        <!-- Materialize CSS -->
        <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
          <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!-- Materialize CSS end -->



{#        <!-- Latest compiled and minified CSS -->#}
{#<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">#}
{##}
{#<script type="text/javascript" src="{% static 'libapp/jquery.min.js'%}"></script>#}
{#<!-- Latest compiled and minified JavaScript -->#}
{#        <link rel="stylesheet" type="text/css" href="{% static 'libapp/css/style.css' %}" />#}
{#            <link rel="stylesheet" type="text/css" href="{% static 'libapp/css/bootstrap.min.css'%}"/>#}
{##}
{#            <script type="text/javascript" src="{% static 'libapp/js/bootstrap.min.js'%}"></script>#}

        <title>MAC Library APP - {% block title %}Welcome!{% endblock %}</title>
    </head>{% endblock %}


<body background="/app/static/css/background1.png">
    <div class="navbar-fixed">
         <nav class="nav-wrapper" style="padding-left: 0">
            <div class="container-fluid">
                     <ul class="nav navbar-nav">
                 <li><a href="{% url 'app:index' %}" class="flow-text">Home</a></li>
                 <li><a href = "{% url 'app:about' %}" class="flow-text">About</a></li>
                         <li><a href = "{% url 'app:myitems' %}" class="flow-text">My Items</a></li>
                    <li><a href = "{% url 'app:searchitem' %}" class="flow-text">Search the library</a></li>
                         <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><span class="flow-text" style="font-size: 180%">Suggestions</span><i class="material-icons right">arrow_drop_down</i></a>
                         <ul id="dropdown1" class="dropdown-content active" style="width: 143px; position: absolute; top: 0; left: 920px; opacity: 1; display: none;">
                    <li><a href = "{% url 'app:suggestions' %}" class="flow-text">Suggestested Items</a></li>
                    <li><a href = "{% url 'app:newitem' %}" class="flow-text">New Sugggestion</a></li>
                             </ul>
                         </li>
                     </ul>
                {% if request.user.username %}
                    <ul class="right">
                    <li style="padding-top: 2.5%">
                        {% for users in userob %}
                             <span class="span-logo"><img class="circular-pic" src="/{{ users.profilepic }}" width="50" height="50"/></span>
                        {% endfor %}
                        </li>
                        <li>
                             <li id="myaccount"><a class="dropdown-button1" href="#!" data-activates="dropdown2"><span class="flow-text" style="font-size: 180%">{{ request.user.first_name }}&nbsp;{{ request.user.last_name }}</span><i class="material-icons right">arrow_drop_down</i></a>
                    <ul id="dropdown2" class="dropdown-content active" style="width: 143px; position: absolute; top: 0; left: 920px; opacity: 1; display: none;">
                        <li><a href="{% url 'app:myacct' %}">Edit Profile</a></li>
                        <li><a href="{% url 'app:setpwd' %}">Change Password</a></li>
                        <li><a href="{% url 'app:logout' %}" class="flow-text">Logout</a></li>
                    </ul>
                    </li>
                 {% else %}
                     <ul class="right">
                         <li><a href = "{% url 'app:login' %}" class="flow-text">Login</a></li>
                         <li><a href = "{% url 'app:register' %}" class="flow-text">Register</a></li>
                     </ul>
                 {% endif %}
                </div>
                </nav>
    </div>
        <div>
{#        {% if request.user.username %}#}
{#            <h4 style="color: whitesmoke">{% block myhdg %}Hello {{ request.user.first_name }} {{ request.user.last_name }} {% endblock %}</h4><br/><br/>#}
{#        {% endif %}#}
        </div>
         <div>
            {% block body_block %}*** {% endblock %}
        <br/><br/><br/><br/>
    <footer class="page-footer" style="position: fixed; bottom: 0; width: 120%; background-color: black">
        <a href="{% url 'app:about' %}" class="grey-text text-lighten-4" style="padding-right: 7%; padding-left: 1%">Find out about this site</a>
            <a href = "{% url 'app:index' %}" class="grey-text text-lighten-4">Click here to return to main page</a><br/><br/>
        </footer>
        </div>

    <!--Import jQuery before materialize.js-->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
      <script>
     $(document).ready(function() {
        $('select').material_select();
    });
          $(".dropdown-button").dropdown();
          $(".dropdown-button1").dropdown();
  </script>
</body>
</html>

templates/libapp/detail.html
{% extends 'libapp/base.html' %}
{% block body_block %}
 <div align="center">
    <div align="center">
    <span style="color: whitesmoke">
    <table class="bordered responsive-table" style="width: 30%;">
    <tbody>
    <tr><td></td><td></td></tr>
    {% if dvd %}
        {% for dvds in dvd %}
            <h3>{{ dvds.title }}</h3>
            <tr><td>Title:</td><td>{{ dvds.title }}</td></tr><br/>
            <tr><td>Type:</td><td>{{ dvds.get_itemtype_display }}</td></tr><br/>
            <tr><td>Publication Year:</td><td>{{ dvds.pubyr }}</td></tr><br/>
            <tr><td>Duedate:</td><td>{{ dvds.duedate }}</td></tr><br/>
            <tr><td>Maker:</td><td>{{ dvds.maker }}</td></tr><br/>
            <tr><td>Duration:</td><td>{{ dvds.duration }}</td></tr><br/>
            <tr><td>Rating:</td><td>{{ dvds.rating }}</td></tr><br/><br/><br/>
    {% endfor %}
    {% else %}
        {% for books in book %}
            <h3>{{ books.title }}</h3>
            <tr><td>Title:</td><td>{{ books.title }}</td></tr><br/>
            <tr><td>Type:</td><td>{{ books.get_itemtype_display }}</td></tr><br/>
            <tr><td>Publication Year:</td><td>{{ books.pubyr }}</td></tr><br/>
            <tr><td>Duedate:</td><td>{{ books.duedate }}</td></tr><br/>
            <tr><td>Author:</td><td>{{ books.author }}</td></tr><br/>
            <tr><td>Category:</td><td>{{ books.get_category_display }}</td></tr><br/><br/><br/>
    {% endfor %}
    {% endif %}
    </tbody>
    </table>
 </span>
    </div>
 </div>
{% endblock %}

templates/libapp/forgotpwd.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div style="padding-top: 3%" align="center">
    <div style="width: 30%;  height: 400px; border-radius: 5px" align="center">
     <div class="col s12 z-depth-5 card-panel">
<form action="." method="post" id="changepwd">{% csrf_token %}
    <h4>Reset Password</h4><br/>
    {% if emailSent == True %}
        <div id="alert1" class="card-panel white lighten-2 green-text" style="line-height: 0; width: 65%;">
   <a href="/app/forgotpwd/" id="close1" class="close green-text" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        Password Sent.
    </div><br/>
    {% endif %}
                <div class="form-group" style="width: 80%;">
                    <input type="text" id="username" name="username" placeholder="Enter Username for retrieving password" required/>
                    <span id="messages"></span><p id="result" style="display: none; visibility: hidden"></p>
                    </div><br/>
                <div class="form-group" style="width: 80%">
                    <button type="submit" id="subuname" name="subuname" class="btn btn-primary">Request Password</button>
                </div>
            </form>
         </div>
        </div>
        </div>
          <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
     <script type="text/javascript">
    var previous_username = '';
    var in_ajax = 0;
    function checkUsername() {
        var username = $("#username").val();
        if ((previous_username != username) && (username != '') && (in_ajax != 1)) {
                in_ajax = 1;
                $("#result").load('/app/checkuname/', {username: username, csrfmiddlewaretoken: '{{ csrf_token }}'}, function() {in_ajax = 0;});
            }
            previous_username = username;
    }
     function checkValues() {
            var val1 = document.getElementById('result').innerHTML;
            if(val1 == 'True'){
                document.getElementById('messages').innerHTML = 'Your password will be sent to your email.';
             $('#subuname').removeAttr('disabled');
            }
            else if(val1 == 'False'){
                document.getElementById('messages').innerHTML = 'Invalid username';
                document.getElementById("subuname").disabled = true;
                $('#subuname').attr('disabled','disabled');
            }
         else {

            }
        }
    $(function() {
            setInterval("checkUsername()", 10 );
            setInterval("checkValues()", 10);
        });
    </script>
{% endblock %}

templates/libapp/index.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div class="collection">
            {% if itemlist %}
        <h4>List of Library items</h4>
        <ul type="">
            {% for item in itemlist %}
            {% if item.itemtype == 'Book' %}
                <li> <a href="{% url 'app:index' %}{{ item.id }}" class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: #e1f5fe">library_books</i>&nbsp; &nbsp;{{ item.title }}</a></li>
                {% elif item.itemtype == 'DVD' %}
                <li> <a href="{% url 'app:index' %}{{ item.id }}" class="collection-item" style="background:none; color: whitesmoke" ><i class="material-icons" style="color: #e1f5fe">play_circle_outline</i>&nbsp;&nbsp;{{ item.title }}</a></li>
                {% else %}
                <li><a href="{% url 'app:index' %}{{ item.id }}" class="collection-item" style="background: none; color: whitesmoke">&nbsp;&nbsp;{{ item.title }}</a><br/></li>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <strong>There are no available items!</strong>
    {% endif %}
    </div><br/><hr/><br/>
    {% if request.session.luckynum  %}
        <h4 style="color: whitesmoke; text-align: center">Your lucky number is: {{ request.session.luckynum }}</h4>
        {% else %}
        <h4 style="color: whitesmoke; text-align: center">Your lucky number is: 0</h4>
    {% endif %}
{% endblock %}

templates/libapp/login.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div style="padding-top: 3%" align="center">
    <div style="width: 25%;border-radius: 5px" align="center">
     <div class="col s12 z-depth-5 card-panel">
        <h4>Please Login!</h4><br/>
             {% if notlogin %}
        <div id="alert1" class="card-panel white lighten-2 red-text" style="line-height: 0; width: 65%;">
   <a href="/app/login/" id="close1" class="close red-text" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        Username or Password Wrong
    </div><br/>
        {% endif %}
    {% if inactive %}
        <div id="alert1" class="card-panel white lighten-2 red-text" style="line-height: 0; width: 65%;">
   <a href="/app/login/" id="close1" class="close red-text" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        User is inactive.
    </div><br/>
        {% endif %}
<form action="." method="post">{% csrf_token %}
    <div style="width: 80%">
        {{ form.as_p }}<br/>
        <button type="submit" class="btn btn-primary btn-block" value="LogIn">LogIN</button><br/>
        <a href="/app/forgotpwd/">Forgot Password?</a>
        </div>
</form>
     </div>
            </div>
    </div>
{% endblock %}

templates/libapp/myacct.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div align="center">
    <div style=" width: 22%"><br/>
     <div class="col s12 z-depth-5 card-panel">
    <form action="/app/myacct/" method="post" id="aclass" enctype="multipart/form-data">{% csrf_token %}
    <div style="width: 70%; border-radius: 5px" align="center">
        <p style="text-align: center; font-size: 35px" class="flow-text">Edit Profile</p>
            {% if added == True %}
        <div id="alert1" class="card-panel white lighten-2 green-text" style="line-height: 0; width: 65%;">
   <a href="/app/myacct/" id="close1" class="close green-text" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        Record Updated.
    </div><br/>
    {% endif %}
        {% if failed == True%}
        <div id="alert1" class="card-panel white lighten-2 red-text" style="line-height: 0; width: 65%;">
   <a href="/app/myacct/" id="close1" class="close" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        Record was not added.
    </div><br/>
    {% endif %}
        <div class="form-group">
            {{ form.as_p }}<br/>
        <button type="submit" class="btn btn-primary btn-lg" value="Submit">Submit</button>
        </div>
        </div>
    </form>
    </div>
    </div>
    </div>
{% endblock %}

templates/libapp/myitem.html
{% extends 'libapp/base.html' %}
{% block body_block %}
{% if itemob or request.user.username %}
    <h5 class="flow-text" style="color: whitesmoke">Checked out items</h5><br/>
    <div class="collection">

    <ul type="">
    {% for item in itemob %}
        {% if item.itemtype == 'Book' %}
        <li><a href="/app/myitems/{{ item.id }}" class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: #e1f5fe">library_books</i>&nbsp;&nbsp;{{ item.title }}</a></li>
        {% elif item.itemtype == 'DVD' %}
         <li><a href="/app/myitems/{{ item.id }}" class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: #e1f5fe">play_circle_outline</i>&nbsp;&nbsp;{{ item.title }}</a></li>
            {% else %}
            <li><a href="/app/myitems/{{ item.id }}" class="collection-item" style="background: none; color: whitesmoke">{{ item.title }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
    {% else %}
    <h4 class="flow-text" style="color: whitesmoke">You need to Login to access this page</h4>
{% endif %}
    </div>
{% endblock %}

templates/libapp/newitem.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div align="center"><br/><br/>
    <div id="main" style="width: 20%" class=" form-inline" align="center">
            <div class="col s12 z-depth-5 card-panel">
                <h4>Add Suggestion</h4>
    <form method="post" action=".">{% csrf_token %}
    {{ form.as_p }}<br/>
    <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>
    </div>
    </div>
{% endblock %}

templates/libapp/searchitem.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div align="center">
    <div style="width: 18%; padding-top: 20px" align="center">
    <div class="col s12 z-depth-5 card-panel">
    <h4 class="flow-text">Search it!!</h4>
    {% if notfound == True %}
       <div id="alert1" class="card-panel white lighten-2 red-text" style="line-height: 0; width: 65%;">
   <a href="/app/searchitem/" id="close1" class="close red-text-text" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        Item not found
    </div><br/>
    {% endif %}
    {% if notinput %}
       <div id="alert1" class="card-panel white lighten-2 red-text" style="line-height: 0; width: 65%;">
   <a href="/app/searchitem/" id="close1" class="close red-text-text" style="vertical-align: inherit; padding-bottom: 120px" data-dismiss="alert" aria-label="close">&times;</a>
        No input given
    </div><br/>
    {% endif %}

    <form action="." method="post">{% csrf_token %}
        {{ form.as_p }}<br/>
        <input type="submit" class="btn btn-primary" value="Submit"><br/>
    </form>
        </div>
        </div>
      </div><br/><br/>
    <h4 style="padding-left: 5px; color: whitesmoke">Search Results:</h4>
    <div class="collection flow-text" style="font-size: 20px"><br/>
        {% if bookob and dvdob%}
            <div style="padding-left: 15px">
            Total {{ bookob.count|add:dvdob.count }} results. <br/><br/>
            <div style="padding-left: 10px">
                Search returned: {{ bookob.count }} books.<br/>
                <ul type="">
                {% for book in bookob %}
                    <li><a href="{% url 'app:index' %}{{ book.id }}" class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: whitesmoke">library_books</i>&nbsp;&nbsp;{{ book.title }}</a></li>
                {% endfor %}
                </ul>
                Search returned: {{ dvdob.count }} dvds.<br/>
                <ul type="">
                {% for dvd in dvdob %}
                    <li><a href="{% url 'app:index' %}{{ dvd.id }}"  class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: whitesmoke">play_circle_outline</i>&nbsp;&nbsp;{{ dvd.title }}</a></li>
                {% endfor %}
                </ul>

        {% elif bookob and not dvdob%}
            Search returned: {{ bookob.count }} books.<br/>
            <ul type="">
            {% for book in bookob %}
                <li><a href="{% url 'app:index' %}{{ book.id }}" class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: whitesmoke">library_books</i>&nbsp;&nbsp;{{ book.title }}</a></li>
            {% endfor %}
            </ul>
            {% elif not bookob and dvdob %}
            Search returned: {{ dvdob.count }} DVDs.<br/>
            <ol>
            {% for dvd in dvdob %}
                <li><a href="{% url 'app:index' %}{{ dvd.id }}" class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: whitesmoke">play_circle_outline</i>&nbsp;&nbsp;{{ dvd.title }}</a></li>
            {% endfor %}
            </ol>
        {% else %}
            <p style="font-size: 130%">No results to display</p>
        {% endif %}
    </div>
    </div>
</div>


{% endblock %}

templates/libapp/suggestions.html
{% extends 'libapp/base.html' %}
{% block body_block %}
    <div class="collection">
    <ul type="">
        {% for slist in itemlist %}
            {% if slist.type == 1 %}
    <li><a href="{% url 'app:suggestions' %}{{ slist.id }}" class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: #e1f5fe">library_books</i>&nbsp;&nbsp;{{ slist.title }}</a></li>
            {% else %}
            <li><a href="{% url 'app:suggestions' %}{{ slist.id }}" class="collection-item" style="background: none; color: whitesmoke"><i class="material-icons" style="color: #e1f5fe">play_circle_outline</i>&nbsp;&nbsp;{{ slist.title }}</a></li>
            {% endif %}
    {% endfor %}<br/>
</ul>
</div>
{% endblock %}

templates/libapp/suggestionsdet.html
{% extends 'libapp/base.html' %}
{% block body_block %}
{% for item in suggestionob %}
    <div align="center">
    <div align="center">
    <span style="color: whitesmoke">
    <h3>{{ item.title }}</h3>
    <table class="bordered responsive-table" style="width: 30%;">
    <tbody>
    <tr><td></td><td></td></tr>
    <tr><td>Title:</td><td>{{ item.title }}</td></tr><br/>
    <tr><td>Publication Year:</td><td>{{ item.pubyr }}</td></tr><br>
    <tr><td>Item Type:</td><td>{{ item.get_type_display}}</td></tr><br/>
    <tr><td>Cost(CAD):</td><td>{{ item.cost }}</td></tr><br/>
    <tr><td>Comments:</td><td>{{ item.comments }}</td></tr><br/>
    <tr><td>Number of Suggestions:</td><td>{{ item.num_interested }}</td></tr><br/><br/>
    {% endfor %}
       </tbody>
        </table>
    </span>

</div></div>
{% endblock %}